Hosts = ["localhost:4242"]
ContextPath = "/api/put"
Method = "POST"
ExpectedResponses = [ 204 ]

MetricsReport = "http://localhost:4240/api/put"

BrokerList = ["localhost:9092"]

Topic = "metrics"

Partitions = []
StartOffset = "newest"
BufferSize = 16
ConsumerGroup = "test_group"
ConsumerID = "test_id"

[Headers]
Content-Type = ["gzip"]
